<a href="https://colab.research.google.com/github/pendracoV/repositorio/blob/main/chapter_04/numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [2]:
import numpy as np
array = np.array([7,8,4,5,1,2])
print(array)

[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [6]:
print(array[-3 :])

[5 1 2]


Using slicing print all the elements except the last one.



In [7]:
print(array[: -1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [11]:
print(array[1:5])

[8 4 5 1]


Reshape the array into a 3 rows and 2 cols (3,2).



In [13]:
newarray=array.reshape([3,2])
print(newarray)

[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [14]:
for x in np.nditer(array):
  print(x)

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [18]:
arr= np.array([0,6,9])
print(arr)

[0 6 9]


Join the two arrays.



In [20]:
import numpy as np

arre = np.concatenate((array, arr))

print(arre)

[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [21]:


odd_number = arre[arre %2 != 0]
print(odd_number)

[7 5 1 9]


Sort the joined array elements.



In [22]:
print(np.sort(arre))

[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [23]:
month_names = np.array(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'])

print(month_names)


['January' 'February' 'March' 'April' 'May' 'June' 'July' 'August'
 'September' 'October' 'November' 'December']


Split the months array in 4 periods of 3 elements each one.



In [24]:
month_names = np.array(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'])

split_periods = np.split(month_names, 4)

for period in split_periods:
    print(period)

['January' 'February' 'March']
['April' 'May' 'June']
['July' 'August' 'September']
['October' 'November' 'December']


Create an array with genre information ['F','M','F','F','M','F'].



In [25]:
genre_info = np.array(['F', 'M', 'F', 'F', 'M', 'F'])

print(genre_info)

['F' 'M' 'F' 'F' 'M' 'F']


Find the indexes where the value is F.



In [26]:
genre_info = np.array(['F', 'M', 'F', 'F', 'M', 'F'])
indexes = np.where(genre_info == 'F')

print(indexes)

(array([0, 2, 3, 5]),)


Store in an array the age information [18,20,19,23,19,20].



In [27]:
age_information = np.array([18, 20, 19, 23, 19, 20])

print(age_information)

[18 20 19 23 19 20]


Create a filter array with values < 20.



In [28]:
age_information = np.array([18, 20, 19, 23, 19, 20])

filter_array = age_information[age_information < 20]

print(filter_array)

[18 19 19]


Change the 3 index element with a value of 22



In [29]:
age_information = np.array([18, 20, 19, 23, 19, 20])
age_information[3] = 22
print(age_information)

[18 20 19 22 19 20]


Print the 4 index element.

In [30]:
age_information = np.array([18, 20, 19, 23, 19, 20])
print(age_information[4])

19
